#!/bin/bash

echo "🚀 DocuMind AI Deployment Script"
echo "================================"

echo ""
echo "📋 Pre-deployment Checklist:"
echo "✅ All API keys configured in .env file"
echo "✅ System tested locally"
echo "✅ Requirements.txt updated"
echo "✅ Deployment configs ready"

echo ""
echo "🌐 Available Deployment Options:"
echo "1. Vercel (Recommended - Fastest)"
echo "2. Railway (Full-featured)"
echo "3. Render (Simple)"
echo "4. Docker (Any platform)"

echo ""
echo "📝 Manual Deployment Steps:"
echo ""
echo "=== VERCEL DEPLOYMENT ==="
echo "1. Go to https://vercel.com"
echo "2. Sign up/Login with GitHub"
echo "3. Click 'New Project'"
echo "4. Import your GitHub repository"
echo "5. Set build command: pip install -r requirements.txt"
echo "6. Set output directory: ./"
echo "7. Add environment variables:"
echo "   - GEMINI_API_KEY"
echo "   - PINECONE_API_KEY"
echo "   - COHERE_API_KEY"
echo "   - VECTOR_DB_PROVIDER=pinecone"
echo "   - RERANKER_PROVIDER=cohere"
echo "8. Deploy!"

echo ""
echo "=== RAILWAY DEPLOYMENT ==="
echo "1. Go to https://railway.app"
echo "2. Sign up/Login with GitHub"
echo "3. Click 'New Project' > 'Deploy from GitHub repo'"
echo "4. Select your repository"
echo "5. Railway will auto-detect Python"
echo "6. Add environment variables in Railway dashboard"
echo "7. Deploy!"

echo ""
echo "=== RENDER DEPLOYMENT ==="
echo "1. Go to https://render.com"
echo "2. Sign up/Login with GitHub"
echo "3. Click 'New' > 'Web Service'"
echo "4. Connect your GitHub repository"
echo "5. Use the render.yaml configuration"
echo "6. Add environment variables"
echo "7. Deploy!"

echo ""
echo "📊 Post-Deployment Testing:"
echo "1. Check health: https://your-app.vercel.app/health"
echo "2. Check frontend: https://your-app.vercel.app/api/"
echo "3. Test document upload"
echo "4. Test query functionality"

echo ""
echo "🎯 Your DocuMind AI is ready for deployment!"
echo "Choose your preferred platform and follow the steps above."
echo ""